features/hw6_hw7
sgmakgg/jsru pull request #4
Opened 2024-10-10 20:34 UTC by sgmakgg

HW6, HW7

2024-10-11 12:57 UTC, zubkov7 requested changes
просьба не смешивать 2 ДЗ в один пул реквест

пройдитесь по проекту и поправьте стилизацию через css модули, а не проп style

2024-10-11 12:57 UTC, zubkov7 commented on react/src/components/authn/authnButton.jsx
> +    >
логика с темой дублируется, необходимо сделать компонент кнопки, который реализуют логику с темой и использовать его в проекте

2024-10-11 12:57 UTC, zubkov7 commented on react/src/components/authn/authnContext.js
> +export const AuthnContext = createContext("unauthorized");
почему Authn, а не Auth?

2024-10-11 12:57 UTC, zubkov7 commented on react/src/components/buttonThemeSwitcher/switcherButton.jsx
> +export const SwitcherButton = ({ children }) => {
из названия компонент не понятно, что переключает кнопка

2024-10-11 12:57 UTC, zubkov7 commented on react/src/components/buttonThemeSwitcher/switcherButton.jsx
> +    <SwitcherContextProvider>
почему тут оборачивается в контекст?

2024-10-11 12:57 UTC, zubkov7 commented on react/src/components/cart/cart.jsx
> +      <h2>{"Cart"}</h2>
можно просто `<h2>Cart</h2>`

2024-10-11 12:57 UTC, zubkov7 commented on react/src/components/cartItem/cartItem.jsx
> +    <div key={itemId} style={{ display: "flex" }}>
для чего тут добавлен key?

2024-10-11 12:57 UTC, zubkov7 commented on react/src/components/cartItem/cartItem.jsx
> +      <span style={{ margin: "0 10px" }}>{dish.name}</span>
почему через style, а не модуль css и классы?

2024-10-11 12:57 UTC, zubkov7 commented on react/src/components/cartItem/cartItem.jsx
> +      <DishCounter topic={""} dishId={itemId} />
зачем передается пустая строка?

2024-10-11 12:57 UTC, zubkov7 commented on react/src/components/cartItem/cartItem.jsx
> +    <div key={itemId} style={{ display: "flex" }}>
и по стилизации вопрос

2024-10-11 12:57 UTC, zubkov7 commented on react/src/components/restaurantspage/RestaurantsPage.jsx
> +        {authnState === "authorized" ? <Cart /> : null}
логичнее унести в Layout

2024-10-11 12:58 UTC, zubkov7 commented on react/src/App.jsx
> +            <ScrollProgressBar viewVariant="accent" />
тоже лучше унести в Layout

2024-10-15 12:50 UTC, sgmakgg commented
> просьба не смешивать 2 ДЗ в один пул реквест
> 
> пройдитесь по проекту и поправьте стилизацию через css модули, а не проп style

Хорошо

2024-10-15 13:07 UTC, sgmakgg commented on react/src/components/buttonThemeSwitcher/switcherButton.jsx
> +    <SwitcherContextProvider>
removed

2024-10-15 13:22 UTC, sgmakgg commented on react/src/App.jsx
> +            <ScrollProgressBar viewVariant="accent" />
done

2024-10-15 13:40 UTC, sgmakgg commented on react/src/components/buttonThemeSwitcher/switcherContextProvider.jsx
> +export const SwitcherContextProvider = ({ children }) => {
renamed

2024-10-15 13:46 UTC, sgmakgg commented on react/src/components/cart/cart.jsx
> +      <h2>{"Cart"}</h2>
done

2024-10-15 14:02 UTC, sgmakgg commented on react/src/components/restaurantspage/RestaurantsPage.jsx
> +        {authnState === "authorized" ? <Cart /> : null}
done

2024-10-15 14:57 UTC, sgmakgg commented on react/src/components/cartItem/cartItem.jsx
> +      <DishCounter topic={""} dishId={itemId} />
removed

2024-10-15 15:03 UTC, sgmakgg commented on react/src/components/cartItem/cartItem.jsx
> +      <span style={{ margin: "0 10px" }}>{dish.name}</span>
i've created css module

2024-10-15 15:04 UTC, sgmakgg commented on react/src/components/cartItem/cartItem.jsx
> +    <div key={itemId} style={{ display: "flex" }}>
styles issue solved

2024-10-15 15:08 UTC, sgmakgg commented on react/src/components/authn/authnContext.js
> +export const AuthnContext = createContext("unauthorized");
Authn => authentication
Authz => authorization

I've changed to Auth

2024-10-15 16:49 UTC, sgmakgg commented on react/src/components/authn/authnButton.jsx
> +    >
done

2024-10-15 18:37 UTC, zubkov7 commented on react/src/App.jsx
> +          <AuthButton />
тоже лучше унести в Layout

2024-10-15 18:38 UTC, zubkov7 commented on react/src/components/cartItem/cartItem.jsx
> +    <div className={classNames(styles.container)}>
для одного класса излишне использовать classNames

2024-10-15 18:40 UTC, zubkov7 commented on react/src/components/themeDependingButton/themeDependingButton.jsx
> +      onClick={() => callback()}
можно просто onClick={callback}

2024-10-15 18:42 UTC, zubkov7 approved these changes
замечания не критичные, можете в следующем дз поправить или тут и замержить сразу

2024-10-15 18:58 UTC, sgmakgg commented on react/src/App.jsx
> +          <AuthButton />
done

2024-10-15 18:59 UTC, sgmakgg commented on react/src/components/themeDependingButton/themeDependingButton.jsx
> +      onClick={() => callback()}
done

2024-10-15 19:01 UTC, sgmakgg commented on react/src/components/cartItem/cartItem.jsx
> +    <div className={classNames(styles.container)}>
done

2024-10-15 19:08 UTC, merged